---
- name: Install MongoDB on macOS
  hosts: localhost
  tasks:
    - name: Install Homebrew (if not installed)
      command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      args:
        creates: /usr/local/bin/brew
      when: not ('/usr/local/bin/brew' is exists)

    - name: Add MongoDB tap to Homebrew
      command: brew tap mongodb/brew
      when: not ('mongodb/brew' is in brew.tap_list)

    - name: Install MongoDB
      command: brew install mongodb/brew/mongodb-community@4.4
      when: not ('mongodb-community' is in brew.list)

    - name: Start MongoDB service
      command: brew services start mongodb/brew/mongodb-community
