---
- name: Install Nginx on macOS
  hosts: localhost
  connection: local # Use become to run commands with elevated privileges

  tasks:
    - name: Update Homebrew
      command: brew update

    - name: Install Nginx
      command: brew install nginx
      args:
        creates: /usr/local/opt/nginx/bin/nginx
      register: nginx_install

    - name: Start Nginx service
      command: brew services start nginx
      when: nginx_install is changed

