- name: Install MongoDB on macOS
  hosts: localhost
  tasks:
    - name: Import the public key used by the package management system
      command: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
      become: yes
      become_user: root

    - name: Add MongoDB repository
      command: echo "deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen" | sudo tee /etc/apt/sources.list.d/mongodb.list
      become: yes
      become_user: root

    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes
      become_user: root

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: latest
      become: yes
      become_user: root
      update_cache: yes
      notify:
        - Start MongoDB

  handlers:
    - name: Start MongoDB
      service:
        name: mongod
        state: started
      become: yes
      become_user: root
