---
- name: Set up webserver on macOS
  hosts: localhost
  become: yes
  become_user: subhamsharma
  become_method: sudo
  become_flags: -H  # Add this line to preserve environment variables
      PATH: "/usr/local/bin:/usr/bin:/bin"

  tasks:
    

    - name: Ensure Nginx is installed
      command: brew install nginx
      changed_when: "'No available formula' not in ansible_previous_result.stderr"

    - name: Start Nginx service
      command: brew services start nginx
      when: "'nginx' not in ansible_previous_result.stdout"

    - name: Enable Nginx to start at boot
      command: sudo brew services start nginx
      when: "'nginx' not in ansible_previous_result.stdout"
