---
- name: Set up webserver on macOS
  hosts: localhost

  tasks:
    - name: Ensure Nginx is installed
      command: brew list | grep -q 'nginx' || brew install nginx
      changed_when: false

    - name: Start Nginx service
      command: brew services start nginx
      when: "'nginx' not in ansible_previous_result.stdout"
