---
- name: Install Nginx on localhost
  hosts: localhost
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Nginx
      apt:
        name: nginx
        state: latest
      when: ansible_os_family == 'Debian'

    - name: Start Nginx service
      service:
        name: nginx
        state: started
      when: ansible_os_family == 'Debian'
