---
- name: Install Nginx on macOS
  hosts: localhost
  connection: local # Use become to run commands with elevated privileges

  tasks:
    - name: Install Nginx
      command: /opt/homebrew/bin/brew install nginx
      

    - name: Start Nginx service
      command: /opt/homebrew/bin/systemctl services start nginx
      

