- name: Install MongoDB on macOS
  hosts: localhost

  tasks:
    

    - name: Add MongoDB tap to Homebrew
      command: brew tap mongodb/brew
      when: not ('mongodb/brew' is in brew.tap_list)
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Install MongoDB
      command: brew install mongodb/brew/mongodb-community@4.4
      when: not ('mongodb-community' is in brew.list)
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Start MongoDB service
      command: brew services start mongodb/brew/mongodb-community
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Check if MongoDB is installed
      command: mongod --version
      ignore_errors: yes
      register: mongodb_check
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Print MongoDB Version
      debug:
        var: mongodb_check.stdout
      when: mongodb_check.rc == 0
