---
- name: Install Nginx on macOS
  hosts: localhost
  connection: local # Use become to run commands with elevated privileges

  tasks:
    - name: Install Nginx
      command: /opt/homebrew/bin/brew install nginx
      args:
        creates: /usr/local/opt/nginx/bin/nginx
      register: nginx_install

    - name: Start Nginx service
      command: /opt/homebrew/bin/brew services start nginx
      when: nginx_install is changed

